# Generated by Django 3.1.3 on 2023-07-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20230712_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='label',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='label',
            field=models.CharField(max_length=1000, verbose_name='question'),
        ),
    ]
